### ISSUE TITLE
Error on Import

### ISSUE THREAD

**Issue by awamser** [moschan/react-native-flip-card#10]
Here are the steps to reproduce the error.

➜  demo-flip-card **react-native --version**
react-native-cli: 0.2.0
react-native: n/a - not inside a React Native project directory

➜  **react-native init DemoFlipCard**
This will walk you through creating a new React Native project in /Users/alan/Sandbox/demo-flip-card/DemoFlipCard
Installing react-native package from npm...
Setting up new React Native app in /Users/alan/Sandbox/demo-flip-card/DemoFlipCard
DemoFlipCard@0.0.1 /Users/alan/Sandbox/demo-flip-card/DemoFlipCard
└── react@15.0.2 

To run your app on iOS:
   cd /Users/alan/Sandbox/demo-flip-card/DemoFlipCard
   react-native run-ios
- or -
  Open /Users/alan/Sandbox/demo-flip-card/DemoFlipCard/ios/DemoFlipCard.xcodeproj in Xcode
  Hit the Run button
  To run your app on Android:
  Have an Android emulator running (quickest way to get started), or a device connected
  cd /Users/alan/Sandbox/demo-flip-card/DemoFlipCard
  react-native run-android

➜  DemoFlipCard **npm i --save react-native-flip-card** 
DemoFlipCard@0.0.1 /Users/alan/Sandbox/demo-flip-card/DemoFlipCard
└── react-native-flip-card@3.2.0
➜  DemoFlipCard **npm --version**
3.8.3
➜  DemoFlipCard **node --version**
v5.10.1

**\* Edit/Added index.io.js
 `import FlipCard from 'react-native-flip-card'`

**\* Update Render /w Simple example on Git

```
<FlipCard>
  {/* Face Side */}
  <View style={styles.face}>
    <Text>The Face</Text>
  </View>
  {/* Back Side */}
  <View style={styles.back}>
    <Text>The Back</Text>
  </View>
</FlipCard>
```
### From IOS Simulator  ( react-native run-ios )

Error in simulator:  Super expression must either be null or a function, not undefined
### From chrome javascript console.

ExceptionsManager.js:61Super expression must either be null or a function, not undefinedhandleException @ ExceptionsManager.js:61
ExceptionsManager.js:61Module AppRegistry is not a registered callable module.handleException @ ExceptionsManager.js:61
ExceptionsManager.js:76Unhandled JS Exception: Super expression must either be null or a function, not undefinedreactConsoleError @ ExceptionsManager.js:76
ExceptionsManager.js:76Unhandled JS Exception: Module AppRegistry is not a registered callable module.reactConsoleError @ ExceptionsManager.js:76

**Comment by moschan** [comment]
@awamser
Thank you for your report!
I will check soon.

**Comment by awamser** [comment]
At first glance this looks like a pretty simple fix, it's due to the breaking out of the components in RN0.25.

```
import React, { Component, PropTypes } from 'react';

import {
  View,
  TouchableWithoutFeedback,
  Animated
} from 'react-native'
```

**Comment by awamser** [comment]
This is a duplicate from #9.
