### ISSUE TITLE
Warning: setState(...): Can only update a mounted or mounting component. 

### ISSUE THREAD

**Issue by flexdhana** [moschan/react-native-flip-card#14]
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the FlipCard component.

Any solution please..

**Comment by alexprice1** [comment]
@flexdhana I put in a PR that should fix this. Just need it accepted:
https://github.com/moschan/react-native-flip-card/pull/15

**Comment by alexprice1** [comment]
@moschan any help?

**Comment by moschan** [comment]
@alexprice91 oh, sorry late reply. I will check.

**Comment by moschan** [comment]
@flexdhana @alexprice91 
hi, I updated this component to `v3.3.1`
Please use this version.

@flexdhana 
Please check your issue if it is fixed or not.

**Comment by alexprice1** [comment]
Awesome! Thank you so much. Will check first thing in the morning.

**Comment by alexprice1** [comment]
Was able to check on my app and this fixes it for me. Thank you!

**Comment by moschan** [comment]
@flexdhana Good! You made it happen :clap:

@flexdhana 
If you can check new component is woking well, please close this issue.
If you still have some problem, please comment here or please create the new issue.

Thank you guys :smiley_cat:

**Comment by flexdhana** [comment]
@moschan Fixed!.. thanks a lot..
