### ISSUE TITLE
Reversed back

### ISSUE THREAD

**Issue by jr-k** [moschan/react-native-flip-card#20]
Hello,

When I'm using your module I got reverse Back side like this: http://puu.sh/teurK/62d7f2dd04.png

Any idea ?

Thanks !

**Comment by jr-k** [comment]
Fixed: For those who got this issue, just apply style "transform: [{rotateY: '180deg'}]" to your back's container.

**Comment by agates4** [comment]
thanks for the fix. situationally happens for me (only android) but I've added android checks to apply that style transform.
