### ISSUE TITLE
Failed style prop type

### ISSUE THREAD

**Issue by kodemi** [moschan/react-native-flip-card#23]
I've got this warning: `Warning: Failed prop type: FlipCard: prop type 'style' is invalid; it must be a function, usually from React.PropTypes.`
RN: 0.40.0

**Comment by gbrlcustodio** [comment]
This may be caused by [this merge](https://github.com/moschan/react-native-flip-card/pull/19). I don't know where is this proptype supposed to come from, there is no React documentation from that.

**Comment by moschan** [comment]
@kodemi 
Thank you for your report.

@gcmartins93 
Let me check again.

**Comment by moschan** [comment]
Hi, I found same error in my environment.
I have fixed that as a hotfix. Please use `v3.3.3`.
