### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by sidevesh** [moschan/react-native-flip-card#24]
I am not able to use this library for some reason.  
`npm i --save react-native-flip-card` get stuck at `loadRequestedDeps: sill install loadAllDepsIntoIdealTree`.  
I am able to install other libraries just fine.

**Comment by moschan** [comment]
Hi @SiDevesh 
I have updated this package. Please try to install again after you remove `node_modules`.
```
rm -rf ./node_modules && npm cache clean && npm i --save react-native-flip-card
```

**Comment by moschan** [comment]
You can re-open this issue if you still have an issue. thanks.
