### ISSUE TITLE
RN 0.42.0 "fixes" transforms which impacts this component 

### ISSUE THREAD

**Issue by rgoldiez** [moschan/react-native-flip-card#26]
I'm seeing the backside of my flip-cards showing a mirror image as identified [here](https://github.com/moschan/react-native-flip-card/issues/20).  But this seems to have surfaced with RN 0.42.0 as noted in the PR below.  If I undo this PR, the backside renders correctly.

https://github.com/facebook/react-native/pull/11992

<img width="372" alt="screen shot 2017-03-11 at 12 15 58 pm" src="https://cloud.githubusercontent.com/assets/10797610/23825721/834ac07e-0654-11e7-8b03-a12e47620bfb.png">

**Comment by boennemann** [comment]
Applying this diff made it work for us again: 

```diff
var transform = []
if (this.props.flipHorizontal) {
-  transform.push({skewY: '180deg'})
+  transform.push({scaleX: -1})
}
if (this.props.flipVertical) {
-  transform.push({skewX: '180deg'})
+  transform.push({scaleY: -1})
}
```

https://github.com/adahealth/react-native-flip-card/commit/dddd0c103240f3cebda036729d37f5532dcc71fb

If there's interest I can open a PR. No idea if it works on older versions of RN, too, though.

**Comment by rgoldiez** [comment]
Thanks @boennemann.  This is working well for me.

**Comment by GetSource1234** [comment]
Got the same problem with RN 0.42.  @boennemann could you please open PR.

**Comment by moschan** [comment]
Hi, sorry for late reply. I have just merged PR, please let me know if you have any problem.

**Comment by moschan** [comment]
This is solved. If you get any problem, feel free to re-open this issue. thanks.
