### ISSUE TITLE
150MB extra build files distributed with npm package

### ISSUE THREAD

**Issue by artdent** [moschan/react-native-flip-card#28]
If you `npm install react-native-flip-card`, you get an extra directory, node_modules/react-native-flip-card/example/ios/build, which weighs 150MB. It looks like an artifact of having run `npm publish` in a non-clean working directory. It'd be good to publish a new release to npm without the unintentional baggage.

**Comment by moschan** [comment]
Hi, @artdent 
I have fixed this problem. I removed example directory from the package. Please try to install the latest version. Thank you!

**Comment by artdent** [comment]
Looks good. Thanks!
