### ISSUE TITLE
Doesnt showing FlipCard

### ISSUE THREAD

**Issue by MirlanJA** [moschan/react-native-flip-card#31]
My version is "react-native-flip-card": "^3.3.6"
`<View style={{flex:1}}>
                  <FlipCard>
                      <View>
                          <Text>The Face</Text>
                      </View>
                      {/* Back Side */}
                      <View>
                          <Text>The Back</Text>
                      </View>
                  </FlipCard>
              </View>`

In the previous version, everything worked, what is the problem?

**Comment by moschan** [comment]
hi @MirlanBekturov 
Thank you for your report. I will check soon.

**Comment by moschan** [comment]
@MirlanBekturov 
I released `v3.4.0`. I fixed lib and upgraded example.
Please check this.

**Comment by moschan** [comment]
You can open if you still have an issue.

**Comment by cwagner22** [comment]
I have the same issue, using 3.4.1

**Comment by cwagner22** [comment]
Created a new issue: #35
