### ISSUE TITLE
onPress never flip the card in many real devices

### ISSUE THREAD

**Issue by cinder92** [moschan/react-native-flip-card#34]
i just tested on LG and Samsung Grand Prime, and Moto G, clickable is not working!

**Comment by cinder92** [comment]
i just figured out, it was for `TouchableWithoutFeedback ` i just changed by `TouchableOpacity`and now issue is gone!

**Comment by vitalybe** [comment]
Good point, it helped! Just make sure, if you use `TouchableOpacity` to set `activeOpacity={1}`

**Comment by moschan** [comment]
@cinder92 Thank you, I will fix soon.

**Comment by moschan** [comment]
Hi @cinder92 @vitalybe 

I update this component to `v3.4.1` to fix this bug. Please use this.

If you still have any bug, feel free to re-open this issue
