### ISSUE TITLE
Preserve height on Flip

### ISSUE THREAD

**Issue by avishayil** [moschan/react-native-flip-card#6]
Hi,
Thank you for the component.
I'm building an articles app.
I'm intending to use this component as a share context menu, means when the user long-presses the card, it would flip to sharing stuff (whatsapp, fb, gmail, etc.)

I figured out how to change the behavior on LongPress, but my problem is that I want to preserve the card height on LongPress so the user would not see any 'jumps' in the layout that would get him out of context.

Of course, the card height depends on the elements inside.

Is there any possibility to preserve the card height on flip, after the card content has been rendered?
Thanks.

**Comment by moschan** [comment]
@avishayil 
Thank you for your issue and apologies for my delayed.

Do you want to preserve the card height "before" flip side? And the height reflect to other side? For example, like this?:

```
Before Flip:
Front side: 120(element height. In your case, it is article?)
Back side: 60(element height, In your case, it is sharing stuff?)

After Flip:
Front side: 120(element height)
Back side: 120(Front side height. do you want to keep article side height?)
```

If this understanding is not fit for your problem, please show me picture or sample code about this problem.

Thank you!

**Comment by avishayil** [comment]
Not exactly.
I want to be able to determine both heights of front side & back side, and set the height based on the larger side, so flip will not cause "jumps" on rendering.

For example:

```
Front side (After in-card elements rendered): 120
Back side (After in-card elements rendered): 140
```

In this case the height would be 140, so card flip would not cause any inconsistencies on layout. 
Hope I was clear this time, and thanks for responding!

**Comment by moschan** [comment]
I see!:smile_cat: I understand what you want to say.

I will check this component and implement function which you want.

Please wait a moment until my work finished.

**Comment by avishayil** [comment]
Thanks for the awesome support!

**Comment by moschan** [comment]
Hi!
so so sorry for late!!

I update this component.
now, you can pass `alignHeight` or `alignWidth` as params(boolean). If you pass `true` to their params, a card component keep height or width of bigger side.

If you have any problem or any request about this update,  you can ask me without hesitation :+1:
