### ISSUE TITLE
Android bug 

### ISSUE THREAD

**Issue by emrullah3737** [moschan/react-native-flip-card#66]
When I use Flipcard on IOS, animation looks good but on Android,  i can't see anything about animation or Back view  :(

**Comment by martinblampied** [comment]
Standard react native, someone creates a package then don't maintain it. I have fixed this in my app by deleting this package and writing my own. Similar example here: https://github.com/browniefed/examples/blob/animated_basic/flip/animatedbasic/index.android.js

**Comment by emrullah3737** [comment]
> Standard react native, someone creates a package then don't maintain it. I have fixed this in my app by deleting this package and writing my own. Similar example here: https://github.com/browniefed/examples/blob/animated_basic/flip/animatedbasic/index.android.js

Thank you for your example.I fixed the bug on android as well. It's caused by style.When ı used the component in style={{ flex: 1 }} and also renderCard component, problem has gone.Before the styles, component looks like well but onPress method didn't work.
