### ISSUE TITLE
Doesnt work with flatlist

### ISSUE THREAD

**Issue by ghost** [moschan/react-native-flip-card#67]
While using FlipCard with flat list it animates all the rendered images on click of any one image.

**Comment by derekbrown** [comment]
I have FlipCard working within a FlatList. If I had to guess, you're likely not binding the flip on a per-instance basis.

**Comment by itsVagabond** [comment]
@derekbrown Can you please share the code to show how to bind the flip on a per-instance basis !

**Comment by derekbrown** [comment]
@itsVagabond Set and toggle the `flip` state inside a separate child component, then use the `renderItem` property of FlatList to render those child components.
