### ISSUE TITLE
Flipboard like view

### ISSUE THREAD

**Issue by ninjz** [moschan/react-native-flip-card#7]
And ideas on how to create a component to switch between a collection of data like in the app Flipboard using this component?

**Comment by moschan** [comment]
Sorry for late reply.

Do you want to use this component with list data?

You can use this component with array. 
I updated example for you. Can you check this example?

If this example don't fit for your idea, can you explain what you want to do using picture or code?

thanks.

**Comment by ninjz** [comment]
Hmm, not quite it 
what i'm thinking is something like this
https://www.youtube.com/watch?v=7lAQ9RsVhY4&nohtml5=False

**Comment by alexprice1** [comment]
@ninjz I would thank you should use `panResponder`.

**Comment by alexprice1** [comment]
You will need to use `transformMatrix`

**Comment by ywcr** [comment]
Are there any implementation？ @ninjz

**Comment by Satwa** [comment]
Any update on this?
