### ISSUE TITLE
Duplicate Style prop is breaking code

### ISSUE THREAD

**Issue by Mattimus333** [moschan/react-native-flip-card#75]
https://github.com/moschan/react-native-flip-card/blob/71b3e0eec2d485ff1a17a44922ecc092d8d9907f/lib/FlipCard.js#L168

You are declaring the style prop twice and it's broken this component on android and every component that uses it.

**Comment by moschan** [comment]
@Mattimus333 
Hi, I just merged PR and released `react-native-flip-card@3.5.5` I hope it helps you 👍
