### ISSUE TITLE
Many times click on card

### ISSUE THREAD

**Issue by moby18** [moschan/react-native-flip-card#8]
Thank you for grate component,  but i have a problem.
When many (2 times and more) times tap on card - flip doesn't respond, no flip animations and doesn't  change state. And its only on device (Nexus 4, iPhone 5), on simulator all work fine. And it stuck on back side.

**Comment by moschan** [comment]
Thank for your issue!

I didn't check behavior carefully on devices.

I will check and respond for you soon.

**Comment by Heaven1619** [comment]
I have same problem on my device, on simulator everything is ok

**Comment by wkrause13** [comment]
This appears to be an issue with TouchableWithoutFeedback, though I can't seem to tie it to any known issue with React Native. I resolved this issue by swapping out TouchableWithoutFeedback for TouchableOpacity. I think you can get the same effect as TouchableWithoutFeedback by setting activeOpacity={1} for TouchableOpacity.

**Comment by moschan** [comment]
This is already solved. Please use the latest version.

If you still get any bug, please open the new issue. thanks.
